name: expense_tracker

description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.20.2
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8

  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0
  firebase_storage: ^13.3.0
  firebase_messaging: ^16.2.0
  firebase_analytics: ^12.3.0
  firebase_crashlytics: ^5.0.2
  google_sign_in: ^6.2.1
  firebase_app_check: ^0.4.3
  sms_autofill: ^2.4.1
  image_picker: ^1.2.2
  flutter_slidable: ^4.0.3
  another_flushbar: ^1.12.32
  uuid: ^4.5.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  mocktail: ^1.0.3

  flutter_launcher_icons: ^0.14.4   # ✔ HERE (correct)

flutter:
  uses-material-design: true

  assets:
    - assets/images/


# 🔥 IMPORTANT: THIS SHOULD BE OUTSIDE flutter
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

