// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlifVibg3cBisJlAijLV-x6gfuoUXUOFY',
    appId: '1:526853902976:web:2515b557cf2c233c144c65',
    messagingSenderId: '526853902976',
    projectId: 'kharchaplus',
    authDomain: 'kharchaplus.firebaseapp.com',
    databaseURL: 'https://kharchaplus-default-rtdb.firebaseio.com',
    storageBucket: 'kharchaplus.firebasestorage.app',
    measurementId: 'G-K78403J9TY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvOgiD7QPmevtt4re22wjb4I0nQsTKTQg',
    appId: '1:526853902976:android:e6292e471b522122144c65',
    messagingSenderId: '526853902976',
    projectId: 'kharchaplus',
    databaseURL: 'https://kharchaplus-default-rtdb.firebaseio.com',
    storageBucket: 'kharchaplus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAckL94PiYYCM0-xwlTAxA4Ixt4EX97rCw',
    appId: '1:526853902976:ios:6f59eb2d30a1db3c144c65',
    messagingSenderId: '526853902976',
    projectId: 'kharchaplus',
    databaseURL: 'https://kharchaplus-default-rtdb.firebaseio.com',
    storageBucket: 'kharchaplus.firebasestorage.app',
    androidClientId: '526853902976-pa51rjq3gjnp7gl3otgerr601m7n1pd9.apps.googleusercontent.com',
    iosClientId: '526853902976-fnbt4idpld3nlk8o2dppkljfd0uinvjn.apps.googleusercontent.com',
    iosBundleId: 'com.nafis.nf.kharchaplus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAckL94PiYYCM0-xwlTAxA4Ixt4EX97rCw',
    appId: '1:526853902976:ios:81fd6a8d6ea4c51f144c65',
    messagingSenderId: '526853902976',
    projectId: 'kharchaplus',
    databaseURL: 'https://kharchaplus-default-rtdb.firebaseio.com',
    storageBucket: 'kharchaplus.firebasestorage.app',
    androidClientId: '526853902976-pa51rjq3gjnp7gl3otgerr601m7n1pd9.apps.googleusercontent.com',
    iosClientId: '526853902976-hilp91i1e144aq3jfr0nl7c2a85f0hu6.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlifVibg3cBisJlAijLV-x6gfuoUXUOFY',
    appId: '1:526853902976:web:59a903e8849b7a81144c65',
    messagingSenderId: '526853902976',
    projectId: 'kharchaplus',
    authDomain: 'kharchaplus.firebaseapp.com',
    databaseURL: 'https://kharchaplus-default-rtdb.firebaseio.com',
    storageBucket: 'kharchaplus.firebasestorage.app',
    measurementId: 'G-2XCYDJNJL4',
  );
}
